### PR TITLE
Import PHPStan doc from Notion

### PR DESCRIPTION
**Pull request by MathieuLamiot**
# Description

Imports the existing documentation about PHPStan (mostly custom rules): https://www.notion.so/wpmedia/PHPStan-custom-rules-144ed22a22f08019b448ddb785b30097?pvs=4

## Type of change

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).
- [ ] Sub-task of #(issue number)
- [ ] Chore
- [ ] Release

## Detailed scenario

NA
### Documentation

NA

### New dependencies

NA

### Risks

NA

# Mandatory Checklist

## Code validation

- [ ] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style

- [ ] I wrote a self-explanatory code about what it does.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unnecessary complexity.
- [ ] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification

Not relevant for this repository.

# Additional Checks
- [ ] In the case of complex code, I wrote comments to explain it.
- [ ] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [ ] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

**Review by wordpressfan — APPROVED** [review]
I've updated the [phpstan page](https://www.notion.so/wpmedia/PHPStan-154ed22a22f080709efed66eeae2d0bf?pvs=4) to have a link to that page:
https://www.notion.so/wpmedia/PHPStan-custom-rules-144ed22a22f08019b448ddb785b30097?pvs=4

**Comment by CrochetFeve0251** [comment]
> I've updated the [phpstan page](https://www.notion.so/wpmedia/PHPStan-154ed22a22f080709efed66eeae2d0bf?pvs=4) to have a link to that page:
> https://www.notion.so/wpmedia/PHPStan-custom-rules-144ed22a22f08019b448ddb785b30097?pvs=4

The handbook isn't supposed to be public? That link is inside our private notion from what I see.

**Comment by MathieuLamiot** [comment]
I think the goal here was to have a link from [our internal Notion](https://www.notion.so/wpmedia/PHPStan-custom-rules-144ed22a22f08019b448ddb785b30097?pvs=4) to [the PHPStan handbook page](https://www.notion.so/wpmedia/PHPStan-154ed22a22f080709efed66eeae2d0bf?pvs=4).
This does not conflict with our engineering handbook being public.

**Comment by MathieuLamiot** [comment]
@Miraeld, kind reminder :)

**Review by Miraeld — APPROVED** [review]

**Pull request merged**
